# default keymap:
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

[mgr]
prepend_keymap = [
  { on   = "w", run  = "close", desc = "Close current tab" },
  { on = "T", run = "tasks:show", desc = "Show task manager" },
  { on = "!",run = 'shell "$SHELL" --block', desc = "Open $SHELL here" },
  { on = "P", run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },
  { on = "p", run = "plugin smart-paste", desc = "Paste into the hovered directory or CWD" },
  { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" }, 
  { on = [ "g", "c" ], run = "plugin git-files", desc = "Show Git file changes" },
  { on = "+", run = "plugin zoom 1", desc = "Zoom in hovered file" },
  { on = "-", run = "plugin zoom -1", desc = "Zoom out hovered file" },
  { on = "M", run = "plugin mount" },
  { on = ["R", "p", "p"], run = "plugin sudo -- paste", desc = "sudo paste" },
  { on = ["R", "P"], run = "plugin sudo -- paste --force", desc = "sudo paste" },
  { on = ["R", "r"], run = "plugin sudo -- rename", desc = "sudo rename" },
  { on = ["R", "p", "l"], run = "plugin sudo -- link", desc = "sudo link" },
  { on = ["R", "p", "r"], run = "plugin sudo -- link --relative", desc = "sudo link relative path" },
  { on = ["R", "p", "L"], run = "plugin sudo -- hardlink", desc = "sudo hardlink" },
  { on = ["R", "a"], run = "plugin sudo -- create", desc = "sudo create" },
  { on = ["R", "d"], run = "plugin sudo -- remove", desc = "sudo trash" },
  { on = ["R", "D"], run = "plugin sudo -- remove --permanently", desc = "sudo delete" }

]

